name: recipe_book
description: "A new Flutter project for a Recipe Book app."

publish_to: 'none' # This prevents accidental publishing to pub.dev

# Versioning
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.6.1

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Enables the use of material icons in the app
  uses-material-design: true

  # Define the assets folder for images
  assets:
    - assets/pasta.jpg
    - assets/pizza.jpg
    - assets/brownie.jpg
    - assets/salad.jpg
